### ISSUE TITLE
Using the command "give basicpipes" does not give the tester any pipes

### ISSUE THREAD

**Issue by samueloluwadoromi** [Terasology/ItemPipes#6]
When using the command `give basicpipes` to get the pipes to build the pipeline, the testers do not receive any pipes and they get an error message (Figure A).

**Figure A:**
![image](https://user-images.githubusercontent.com/42849955/56164583-9e796600-5f96-11e9-9a33-e0f71afdc719.png) 

**Repo Steps:**

1. Create a new world with the "**Itempipes**" module activated

2. Open the in-game command prompt with the **f1** button on your keyboard. 

3. In the in-game command prompt type in the command `give basicpipes` and press enter

**Expected**
The command `give basicpipes` is meant to add pipes into the toolbar

**Actual**
The command `give basicpipes` gives out an error message shown in Figure A

**Comment by e-aakash** [comment]
The correct command is `give basicpipe`. 
That would give you some pipes to create the pipeline
